name: EBAC CI Mobile

on:
  push:
    branches: [master]


  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Dependencies
        run: npm i
      - name: Run Tests
        run: npm t
      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
